name: Verilog Build and Analysis

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: |
        echo "Install required dependencies"
        sudo apt-get update
        sudo apt-get install iverilog
        sudo apt-get install verilator

    - run: |
        echo "Set executable permission on script file"
        chmod +x build/sh
        chmod +x ./ClockDivider.v

    - run: |
        echo "Run, Build Application using script"
        ./build/sh
